### ISSUE TITLE
No module named 'mmdet3d.models'

### ISSUE THREAD

**Issue by ChiefGodMan** [HXMap/HRMapNet#1]
The folder tree in hrmapnet is following:
├── mmdet3d
│   ├── __init__.py
│   ├── __pycache__
│   ├── apis
│   ├── core
│   ├── datasets
│   ├── ops
│   ├── utils
│   └── version.py

but in official https://github.com/open-mmlab/mmdetection3d the folder tree is 
![image](https://github.com/user-attachments/assets/46320fe8-939c-49d6-8284-ce3c55724f6f)
The error is not found models.

**Comment by fishmarch** [comment]
Thanks for pointing out this. Some folders were not uploaded by mistake...
