### ISSUE TITLE
map fuse_method 

### ISSUE THREAD

**Issue by Pocan0** [HXMap/HRMapNet#10]
1. 这里用nuscense trainmap训练，在hrmapnet_maptrv2_nusc_r50_24ep_trainmap.py中map_cfg设置fuse_method='prob'，但是在global_map.py check_map中，只要是训练状态，fuse_method就变成all了。然后train_map.pt中值范围是99-130，这样就导致local_map在除以255以后，肯定会小于0.8，这样预训练的train_map.pt是不是就没用了

def check_map(self, device, epoch, status):

        if status == 'train':

            self.fuse_method = 'all'   # To keep consistent with our initial setting

        else:

            self.fuse_method = self.fuse_method_val

**Comment by fishmarch** [comment]
The 'train_map.pt' is built by running training data with a trained model, just like 'test_map.pt'. Thus, I remember it is also a map built using fuse_method='prob'.

**Comment by Pocan0** [comment]
是的就是这个train_map.pt是通过prob生成的图，就是在使用hrmapnet_maptrv2_nusc_r50_24ep_trainmap.py训练的时候，发现training的时候，fuse_method总是设置为all了，和cfg设置的没有关系，这样加载预先生成的train_map.pt是不是就没有起作用了

**Comment by fishmarch** [comment]
Oh, 'hrmapnet_maptrv2_nusc_r50_24ep_trainmap.py' is just for evaluation not for training. For training, I did not load any map. If you would like to load a map for training, you can delete the codes you mentioned, or build a new map using fuse_method = 'all'.

**Comment by Pocan0** [comment]
OK，thanks~
