### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by save-me-ctrl-c** [HXMap/HRMapNet#11]
Hello, may I ask whether the nuscenev1.0full dataset uses the 'mini' version or 'Trainval'? The latter seems to be too large, and I would like to confirm which one it is.

**Comment by fishmarch** [comment]
We use v1.0-trainval, we did not try nuscenes-mini.

**Comment by save-me-ctrl-c** [comment]
Excuse me, I have another question. Are the processing of the three datasets interrelated? Can the model be used with CAN bus data alone?Many thanks for your response

**Comment by fishmarch** [comment]
What's the meaning of using CAN bus data alone, don't use any camera data?
