### ISSUE TITLE
target node [(15.0, 2.355), (15.0, -2.636), (4.167, -30.0), (-15.0, 15.813), (0.284, -30.0)] not in graph

### ISSUE THREAD

**Issue by ailias** [HXMap/HRMapNet#2]
When I prepare nuscenes datas with 'python tools/maptrv2/custom_nusc_map_converter.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data' then it cause following error:
![image](https://github.com/user-attachments/assets/33364826-7e2a-4eb5-9945-eb37828435c6)

**Comment by fishmarch** [comment]
This is a bug from MapTRv2, please refer to https://github.com/hustvl/MapTR/issues/93. It seems you need to update networkx.
