### ISSUE TITLE
historical map prepare

### ISSUE THREAD

**Issue by Jenny0420** [HXMap/HRMapNet#4]
Hi,how can i make test_map.pt or train_map.pt by myself dataset?

**Comment by fishmarch** [comment]
Hi! You need to firstly train and test the model on your dataset just the same as using MapTRv2. Then you can modify some codes using https://github.com/HXMap/HRMapNet/blob/69857f2324328c382d77bfb692f4011dc679cba9/projects/mmdet3d_plugin/hrmap/global_map.py#L244 to save your maps.

**Comment by Jenny0420** [comment]
my data format is the same as nus-data ,can i use nuscenes data model ckpt to infer myself data and use this interface to make the map.pt and then train mydata by this map.pt?

**Comment by fishmarch** [comment]
Currently, we train the model from an empty map for fair comparison with other methods. The map will be constructed gradually during the training for each epoch. Thus you do not need to prepare a map to train your own model. 

But of course, for practical usage, this is not an optimal training setting. Train and test with a pre-built map may achieve better performance. For your purpose, I think you can firstly test the model trained by nuscenes data on your own data, if the results are good enough, you can train your own model using this pre-built map. If the results are not good, you can still train from the empty map as our default setting.

**Comment by Jenny0420** [comment]
yeah,,

**Comment by ailias** [comment]
How to update one global map with multi gpu training mode? Currentlly each of them create self global map and update it.
