### ISSUE TITLE
load checkpoint from local path: ./path/to/ckpts.pth

### ISSUE THREAD

**Issue by Fengqi-Yang** [HXMap/HRMapNet#9]
<img width="597" alt="2024-09-26 213817" src="https://github.com/user-attachments/assets/9858acca-fd9f-4e57-b467-c9938754e89c">

Readme did not tell me where to download the modified file. Do I need to create my own folder for './path/to'?

**Comment by fishmarch** [comment]
You need to download the model, and specify the path to that model (.pth file) in the command.
